
name: Update datasets (2020,2020/21)

on:
  schedule:
    # note: * is a special character in YAML so you have to quote this string
    #  see cron guru for more examples / help on syntax
    #    ->  https://crontab.guru/examples.html
    - cron:  '0 5 * * TUE'       #  every Tuesday at 5 am (utc?)
  workflow_dispatch:
    ### for testing / debugging allow "manual" start


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Run install / adduser
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        bundle install
        yo adduser

    - name: Run ssh_clone
      run:  yo clone

    - name: Run write
      run:  yo -r ./write write

    - name: Run ssh_push
      run:  yo push

